sudo: false
language: php

matrix:
    include:
        - php: 5.6
        - php: 7.0
        - php: 7.1
    fast_finish: true
    allow_failures:
        - php: nightly

before_script:
  - composer install

script:
  - composer cs-check
  - composer test

cache:
  directories:
    - $HOME/.composer/cache
